In [ ]:
#test 1

In [3]:
# We import NumPy into Python
import numpy as np

# We create a 1D ndarray that contains only integers
x=np.array([1,2,3,4,5])

# Let's print the ndarray we just created using the print() command
print('x=',x)

# We print information about x
print('the shape of element:',x.shape)
print('the shape of element:',type(x))
print("the dtype of element:",x.dtype)

x= [1 2 3 4 5]
the shape of element: (5,)
the shape of element: <class 'numpy.ndarray'>
the dtype of element: int32


In [ ]:
# We create a rank 1 ndarray that only contains strings
x=np.array(['Hello ,World'])

# We print x
print()
print('x=',x)
print()

# We print information about x shape type and dtype
print("the shape of element:",x.shape)
print("the type of element:",type(x))
print("the dtype of element:",x.dtype)

In [ ]:
# We create a rank 1 ndarray from a Python list that contains integers and strings
x=np.array([1,2,'Hello, World'])
# We print the ndarray
print(x)

# We print information about x shape type and dtype
print("the shape of element:",x.shape)
print("the type of element:",type(x))
print("the dtype of element:",x.dtype)

In [ ]:
# We create a rank 2 ndarray that only contains integers
y=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

# We print the ndarray
print(y)

# We print information about x shape type and dtype
print("the shape of element:",y.dtype)
print("the type of element:",type(y))
print("the dtype of element:",y.dtype)

In [ ]:
# We create a rank 1 ndarray that contains integers
x=np.array([1,4,5,4])

# We create a rank 1 ndarray that contains floats
y=np.array([12.12,3.3,2.22,54.5])
# We create a rank 1 ndarray that contains integers and floats
z=np.array([11,1,2.2,3.65])
# We print the dtype of each ndarray
print("the dtype of element is x:",x.dtype)
print("the dtype of element is y:",y.dtype)
print("the dtype of element is z:",z.dtype)

In [2]:
#Test 2

In [10]:
# We create a rank 1 ndarray that contains integers from 1 to 5
x=np.array([1,2,3,4,5])

# Let's access some elements with positive indices
print("the first element:\n",x[0])
print("the last element:\n",x[4])

# Let's access the same elements with negative indices
print("the first element:\n",x[-1])
print("the last element:\n",x[-5])


the first element:
 1
the last element:
 5
the first element:
 5
the last element:
 1


In [20]:
# We change the fourth element in x from 4 to 20
x[3]=20
print(x)

[ 1  2  3 20  5]


In [13]:
# We create a 3 x 3 rank 2 ndarray that contains integers from 1 to 9
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(X)

# Let's access some elements in X
print("the first element:\n",X[0,0])
print("the last element:\n",X[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
the first element:
 1
the last element:
 9


In [14]:
# We change the (0,0) element in X from 1 to 20
X[0,0]=20
print(X)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [21]:
# We create a rank 1 ndarray 
x=np.array([1,2,3,4,5])
# We create a rank 2 ndarray
y=np.array([[1,2,3],[4,5,6],[7,8,9]])
# We delete the first and last element of x
v=np.delete(x,[0,4])
print("\n",v)

# We delete the first row of y
s=np.delete(y,0,axis=0)
print("\n",s)

# We delete the first and last column of y
a=np.delete(y,[0,2],axis=1)
print("\n",a)


 [2 3 4]

 [[4 5 6]
 [7 8 9]]

 [[2]
 [5]
 [8]]


In [25]:
# We append the integer 6 to x
v=np.append(x,6)
print("\n",v)
# We append the integer 7 and 8 to x
s=np.append(x,[7,8])
print("\n",s)

# We append a new row containing 7,8,9 to y
g=np.append(y,[7,8,9])
print("\n",g)

# We append a new column containing 9 and 10 to y
h=np.append(y,[[9],[10]])
print("\n",h)


 [1 2 3 4 5 6]

 [1 2 3 4 5 7 8]

 [1 2 3 4 5 6 7 8 9 7 8 9]

 [ 1  2  3  4  5  6  7  8  9  9 10]


In [26]:
#Test 3

In [52]:
# We create a 5 x 5 ndarray that contains integers from 0 to 24
X=np.arange(25).reshape(5,5)
print(X)

# We use Boolean indexing to select elements in X: like greater 10 and less equal 7
print("greater than 10:\n",X[X>10])
print("less and equal to 7:\n",X[X<=7])
print("greater than 10 and less than 17:\n",X[(X > 10) & (X < 17)])

# We use Boolean indexing to assign the elements that are between 10 and 17 the value of -1
X[( X > 10 ) & ( X < 17 )] = -1
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
greater than 10:
 [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
less and equal to 7:
 [0 1 2 3 4 5 6 7]
greater than 10 and less than 17:
 [11 12 13 14 15 16]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


In [36]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4,5])

# We create a rank 1 ndarray
y = np.array([6,7,2,8,4])

# We use set operations to compare x and y: intersect,union
print("element of x,y\n",np.intersect1d(x,y))
print("all element \n",np.union1d(x,y))

element of x,y
 [2 4]
all element 
 [1 2 3 4 5 6 7 8]


In [55]:
# We create an unsorted rank 1 ndarray
x=np.random.randint(1,11,size=(10,))
print(x)

# We sort x and print the sorted array using sort as a function.
a=np.sort(x)
print("sorted value:\n",a)
# We sort x but only keep the unique elements in x
b=np.sort(np.unique(x))
print(x)

[ 1  2  4 10  4  4  5  1 10  9]
sorted value:
 [ 1  1  2  4  4  4  5  9 10 10]
[ 1  2  4 10  4  4  5  1 10  9]


In [30]:
#Test 4

In [41]:
# We create two rank 1 ndarrays
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])

# We perfrom basic element-wise operations using arithmetic symbols and functions
print("x+y",x+y)
print("sub",subtract(x,y))

x+y [ 6.5  8.5 10.5 12.5]


NameError: name 'subtract' is not defined