In [3]:
#mean normalization and data seperation

In [4]:
import numpy as np

In [5]:
# create a 100 X 20 ndarray with random integer between 0 to 5000

x = np.random.randint(5000,size=(1000,20))
print(x)

[[3195 4980  862 ... 4440 4502  281]
 [2522 4114 3734 ...  720  270 2411]
 [1621 3525   78 ...  156 2041 2374]
 ...
 [2780  792 3241 ... 3502 2437 4131]
 [2104  338   99 ... 2840 4656 1596]
 [4451 4667 2436 ...   57 1680 2737]]


In [6]:
#average value of each column of x

ave_cols = np.mean(x,axis=0)
print(ave_cols)

[2554.319 2561.07  2507.497 2560.929 2489.241 2563.315 2598.938 2445.761
 2526.74  2491.715 2463.704 2539.661 2541.645 2432.062 2468.069 2514.542
 2480.609 2547.675 2523.326 2449.315]


In [7]:
# stardard deviation of each column of x

std_cols = np.std(x,axis=0)
print(std_cols)

[1446.36150434 1451.59007888 1453.8924183  1442.80872743 1460.10335282
 1428.06639124 1437.72836731 1425.17177767 1452.31149496 1407.06406598
 1426.07883316 1449.4116924  1435.58546906 1439.69259224 1447.92341726
 1442.31709767 1472.03520546 1433.59705335 1429.85327419 1411.57445421]


In [8]:
# print shape of average mean

ave_cols.shape

(20,)

In [9]:
# print shape of stardard deviation

std_cols.shape

(20,)

In [10]:
# mean normalization of x

X_norm =(x - ave_cols/std_cols)

# print all average from X_norm
print(X_norm)

[[3193.23396918 4978.23567959  860.2753215  ... 4438.2228793
  4500.23525529  279.26483471]
 [2520.23396918 4112.23567959 3732.2753215  ...  718.2228793
   268.23525529 2409.26483471]
 [1619.23396918 3523.23567959   76.2753215  ...  154.2228793
  2039.23525529 2372.26483471]
 ...
 [2778.23396918  790.23567959 3239.2753215  ... 3500.2228793
  2435.23525529 4129.26483471]
 [2102.23396918  336.23567959   97.2753215  ... 2838.2228793
  4654.23525529 1594.26483471]
 [4449.23396918 4665.23567959 2434.2753215  ...   55.2228793
  1678.23525529 2735.26483471]]


In [11]:
# print all minimum value from X_norm

print(X_norm.min(axis=0))

[-0.76603082  0.23567959  1.2753215   5.22503915 -1.7048389   2.20504494
  1.1923303   6.28388336  0.26019417 -1.77086109  6.27239284 -1.75220126
  8.22954115 -1.68929257  0.29544231 -1.74340442 -1.68515603 -0.7771207
 -0.76474471  2.26483471]


In [12]:
# print a maximum value from X_norm
print(X_norm.max(axis=0))

[4995.23396918 4980.23567959 4989.2753215  4994.22503915 4992.2951611
 4996.20504494 4995.1923303  4997.28388336 4997.26019417 4994.22913891
 4997.27239284 4987.24779874 4995.22954115 4991.31070743 4997.29544231
 4986.25659558 4997.31484397 4996.2228793  4993.23525529 4991.26483471]


In [13]:
# data seperation

In [14]:
# We create a random permutation of integers 0 to 4

np.random.permutation(5)

array([2, 1, 3, 0, 4])

In [16]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`

row,col =X_norm.shape
row_indices =np.random.permutation(row)
print(row_indices)

[786  94 249 747 801 441 491 632 993   0 885 464 973 481 370 879   2 555
 861  42  78 567 397 837 326   6 924 781  67 354 338 528 608  76 735 270
 320 337 433 455 374 753 484 308 723 970 444 960 709 239  11 731 958   1
 552 699 499  47 869 461  49 888 820 575 858 253 106 649 110 643 317  74
 686 654 878 873 417 402 497 100 619 899 474 199 829 408 510 549 384 897
  26 610 626 600 576 965 559   8 815 414 910 167 816 604 375  52 945 226
 618 564 598 908 849 139  82 932 639  27 405 158 660 508 921 482 273 990
 310  22 134 652 271 949 693 292 214 592 853 533 512 930 411 914 640 197
 777 733 724 330  91 694 839 568 185 691  60 739 430 638 655 306 982 832
 458 864 123 983 847 165 593 755 325 364 615 477 585 964  12 168 923   7
  85 211 390 725  55 987 138 304 347 148 683 237 662 111 120 187 124 726
  90 622 717 242 918 437 363 606 141 212 541  68 284 789 599 617 372 738
 674 942 866  56 452   4 603 868 465 216 702 901 554 798 240 241 587 186
 845 447  48 498 312 195 865 170 140 503 881 368 85

In [18]:
# Create a Training Set

X_train = X_norm[row_indices[0:600]]
print(X_train)

[[4843.23396918 1338.23567959  735.2753215  ... 4291.2228793
  4958.23525529 2156.26483471]
 [1035.23396918 4769.23567959 1764.2753215  ... 4656.2228793
  2297.23525529 4924.26483471]
 [1472.23396918 3593.23567959 3473.2753215  ... 3984.2228793
  3809.23525529 1980.26483471]
 ...
 [3212.23396918 1491.23567959 2568.2753215  ... 1398.2228793
   310.23525529 1828.26483471]
 [2778.23396918  790.23567959 3239.2753215  ... 3500.2228793
  2435.23525529 4129.26483471]
 [3448.23396918 4007.23567959 4447.2753215  ... 1749.2228793
  3885.23525529  352.26483471]]


In [19]:
# Create a Cross Validation Set

X_crossVal = X_norm[row_indices[600:800]]
print(X_crossVal)

[[4505.23396918 4907.23567959  869.2753215  ...  667.2228793
  3983.23525529 2235.26483471]
 [2903.23396918 3466.23567959 2593.2753215  ... 1796.2228793
  3435.23525529  883.26483471]
 [1052.23396918 4205.23567959  132.2753215  ... 4136.2228793
   879.23525529 2094.26483471]
 ...
 [1223.23396918 2955.23567959  566.2753215  ... 3754.2228793
  1113.23525529 3362.26483471]
 [ 409.23396918 1360.23567959  838.2753215  ... 1220.2228793
  3887.23525529    8.26483471]
 [1429.23396918 3190.23567959 3687.2753215  ... 2254.2228793
  1156.23525529  774.26483471]]


In [20]:
# Create a Test Set

X_test = X_norm[row_indices[800:1000]]
print(X_test)

[[4486.23396918  138.23567959 2073.2753215  ... 2224.2228793
  1866.23525529 3430.26483471]
 [1535.23396918 2368.23567959 3164.2753215  ... 3706.2228793
   681.23525529 1619.26483471]
 [3747.23396918 3000.23567959 3586.2753215  ... 1275.2228793
  2071.23525529 1781.26483471]
 ...
 [1825.23396918 2498.23567959 3122.2753215  ... 2860.2228793
  1619.23525529 2307.26483471]
 [2130.23396918  837.23567959 1502.2753215  ... 1615.2228793
  2014.23525529 3802.26483471]
 [ 899.23396918 1563.23567959 1440.2753215  ... 2573.2228793
  1206.23525529 2507.26483471]]


In [21]:
X_train.shape

(600, 20)

In [22]:
X_crossVal.shape

(200, 20)

In [23]:
X_test.shape

(200, 20)

In [ ]:
# End